worker_processes 1;

events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server auth-service:4000;
    }

    upstream black_list_service {
        server black-list-server:11000;
    }
    
    upstream cac_service {
        server cac-server:9000;
    }
    
    upstream files_service {
        server files-server:3001;
    }
    
    upstream fss_service {
        server fss-server:9001;
    }
    
    upstream log_service {
        server log-server:4321;
    }
    
    upstream mac_service {
        server mac-server:9003;
    }
    
    upstream socket_service {
        server socket-server:9002;
    }
    
    upstream unit_symbols_service {
        server unit-symbols:5000;
    }
    
    upstream frontend {
        server frontend:3000;
    }

    server {
        listen 8080;
        auth_request /internal/validate;
        error_page 401 = @login;

        location = /internal/validate {
            internal;
            proxy_pass http://auth_service/authentication/validateUpn;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;
            proxy_set_header X-Original-Method $request_method;
        }

        location @login {
            return 302 http://frontend/login;
        }
        location /api/auth/ {
            auth_request off;
            proxy_pass http://auth_service/;
        }

        location / {
            auth_request off;
            proxy_pass http://frontend/;
        }

        location /api/black-list-server/ {
            proxy_pass http://black_list_service/;
        }

        location /api/cac-server/ {
            proxy_pass http://cac_service/;
        }

        location /api/files-server/ {
            proxy_pass http://files_service/;
        }

        location /api/fss-server/ {
            proxy_pass http://fss_service/;
        }

        location /api/log-server/ {
            proxy_pass http://log_service/;
        }

        location /api/mac-server/ {
            proxy_pass http://mac_service/;
        }

        location /api/socket-server/ {
            proxy_pass http://socket_service/;
        }

        location /api/unit-symbols/ {
            proxy_pass http://unit_symbols_service/;
        }
    }
}